### ISSUE TITLE
OSS-Lizenzen Übersicht

### ISSUE THREAD

**Issue by kerriestauffer** [digital-sustainability/open-source-circle#3]
Wie während #1 besprochen, ist eines der festgelegten Ziele (auf [Miro-Board](https://miro.com/app/board/uXjVPubTj30=/?share_link_id=366214360558) festgehalten) eine OSS-Lizenzen Übersicht zu erstellen. Diese sollte wichtige Hinweise enthalten bezüglich der Nutzung von OSS mit gewissen Lizenzen wie auch zur Veröffentlichung von eigener OSS unter einer bestimmten Lizenz

**Comment by kerriestauffer** [comment]
To do:

- [ ] Lizenzenauswahl treffen
- [ ] Dokument für Nutzungshinweise erstellen
- [ ] Merkblatt mit Hinweisen bezüglich Veröffentlichung
- [ ] Von Person mit juristischem Hintergrund überprüfen lassen

**Comment by MarkusTiede** [comment]
Hallo @kerriestauffer - solche Listen gibt es mMn schon "zu Hauf" bspw.
- Uebersicht & generelle Einordnung: https://github.com/todogroup/ospo-career-path/blob/main/OSPO-101/module5/README.md#lesson-open-source-license-types
- Detaillierte Liste der (approved) OSI Lizenzen: https://opensource.org/licenses/
- CC Lizenzen: https://creativecommons.org/licenses/?lang=de

**Comment by kerriestauffer** [comment]
Hallo @MarkusTiede - danke dir für den Hinweis und die Links! Ich werde mich da gerne reinlesen um zu sehen, ob sie alle unsere besprochenen Punkte abdecken
